apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::070489781351:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GICED56IXZ5Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::070489781351:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-01T20:21:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1589"
  uid: 2e57185b-fa20-4586-9f11-706a0e30e345
